INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Apple AirPods Pro (Wireless Earbuds)', 249);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Samsung Galaxy Watch 6 (Smartwatch)', 299);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('JBL Flip 6 (Portable Bluetooth Speaker)', 129);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Philips XXL Air Fryer', 349);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Roborock S7 MaxV (Robot Vacuum Cleaner)', 799);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Smeg Retro Electric Kettle', 149);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Michael Kors Jet Set Tote Bag', 298);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Fossil Gen 6 Smartwatch', 299);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Ray-Ban Aviator Sunglasses', 161);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Atomic Habits by James Clear (Book)', 14);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Arteza Acrylic Paint Set (24 Colors)', 29);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Catan Board Game', 49);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Chanel Coco Mademoiselle Perfume', 135);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Pandora Moments Bracelet', 65);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('La Mer Moisturizing Soft Cream', 190);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('PopSocket Phone Grip', 10);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Ember Temperature Control Mug', 99);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Bedsure Sherpa Fleece Blanket', 29);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Nintendo Switch OLED Model', 349);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('GoPro HERO11 Black', 399);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Kindle Paperwhite (11th Gen)', 139);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Dyson Supersonic Hair Dryer', 429);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('LEGO Creator Expert Assembly Square', 299);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Apple MacBook Air M2', 1199);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Sony WH-1000XM5 Noise Cancelling Headphones', 399);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Instant Pot Duo 7-in-1 Electric Pressure Cooker', 99);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Bose SoundLink Revolve+ II Bluetooth Speaker', 329);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Fitbit Charge 6 Fitness Tracker', 159);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Canon EOS R10 Mirrorless Camera', 979);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Ooni Koda 12 Gas Pizza Oven', 399);
