-- Sequence
CREATE SEQUENCE WISHDB.PRODUCTS_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER WISHDB.PRODUCTS_TRG
BEFORE INSERT
ON WISHDB.PRODUCTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PRODUCT_ID
  :new.PRODUCT_ID := PRODUCTS_SEQ.nextval;
END PRODUCTS_TRG;
/


-- Sequence
CREATE SEQUENCE WISHDB.USER_S2_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER WISHDB.USER_S2_TRG
BEFORE INSERT
ON WISHDB.USER_S
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column USER_ID
  :new.USER_ID := USER_S2_SEQ.nextval;
END USER_S2_TRG;
/

-- Sequence
CREATE SEQUENCE WISHDB.WISH_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER WISHDB.WISH_TRG
BEFORE INSERT
ON WISHDB.WISH
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column WISH_ID
  :new.WISH_ID := WISH_SEQ.nextval;
END WISH_TRG;
/

