CREATE OR REPLACE TRIGGER trg_delete_wish
BEFORE DELETE ON WISH
FOR EACH ROW
DECLARE
    CURSOR cur_contributions IS
        SELECT CONTRIBUTOR_NAME, AMOUNT
        FROM CONTRIBUTION
        WHERE WISH_ID = :OLD.WISH_ID;
BEGIN
    FOR rec IN cur_contributions LOOP
        UPDATE USER_S
        SET POINTS = POINTS + rec.AMOUNT
        WHERE USER_NAME = rec.CONTRIBUTOR_NAME;
    END LOOP;

    DELETE FROM CONTRIBUTION
    WHERE WISH_ID = :OLD.WISH_ID;
END;
/
